### ISSUE TITLE
undefined method `image_metadata' for nil:NilClass

### ISSUE THREAD

**Issue by ankkho** [assembler/attachinary#98]
I am using attachinary with rails 4.1.1 , but stuck with this issue and not able to solve it, can someone please guide me how to fix this issue...

This error come from: form.html.erb page 

<% form_for :Book do |f| %>
<%= f.attachinary_file_field :image %>
<%= f.submit %>
<% end %>

**Comment by tocker** [comment]
Hi @anknet 

This probably means that you didn't use `has_attachment` in your model to define the `image` field.
For example:

```ruby
class Book < ActiveRecord::Base
  has_attachment :image
end
```

**Comment by rgbskills** [comment]
I have the same problem, and I have the field defined in my model :(

**Comment by scott** [comment]
I ran into this issue with rails 4.2.  The error reports `f.` is nil. Seems like a bug in attachinary, I didn't really look into it though.  It appears that the association is not being built for new objects, which means you have to use:

`attachinary_file_field_tag 'topic[images]', @topic, :images`

instead of 

`f.attachinary_field_field`

it will work!

**Comment by ptolemybarnes** [comment]
Problem also arises when using the `fields_for` helper. Attachinary gets to here:
```ruby 
# attachinary-1.3.1/lib/attachinary/view_helpers.rb @ line 7

def builder_attachinary_file_field_tag(attr_name, builder, options={})
  options = attachinary_file_field_options(builder.object, attr_name, options)
  builder.file_field(attr_name, options[:html])
end
```

But `builder.object` will be nil when using `fields_for`.

**Comment by fordfischer** [comment]
Any updates on this? I would love to know how to have an attachinary field on an association in a `fields_for` block.

**Comment by designstuhl** [comment]
@scott Your method worked for me as well. I changed my `= f.attachinary_file_field :avatar` to `= attachinary_file_field_tag 'room[avatar]', @room, :avatar` and it appears to be working now. At least it cleared the error. Now I have to work at getting the image to display after upload. 

Thanks for the suggestion. Seems to have saved me a ton of work and headaches.

**Comment by designstuhl** [comment]
UPDATE: So for my instance it turned out that it wasn't the attachinary_file_field that was to blame. When I changed the architecture for my model to belong to a parent organization my form paths got messed up. Despite the fact that I was pointing to `organization_room_path` , when I inspected the form in the browser my form url was set to the edit path instead of the update path. When I submitted my form each time it would simply refresh the page. 

I had to change my `form_for` structure like this:

OLD:
`= form_for organization_room_path, html: {class: 'my-class-here'}`
NEW: 
` = form_for @room, url: organization_room_path, html: {class: 'my-class-here'}`

I hope this helps someone else in a similar situation.
